name: clock_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  vector_math: ^2.1.2
  intl: ^0.17.0
  get_storage: ^2.0.3
  device_preview: ^1.1.0
  flutter_screenutil: ^5.5.4
  duration_picker: ^1.1.0+1
  percent_indicator: ^4.2.2
  audiofileplayer: ^2.1.0
  flutter_local_notifications: ^12.0.2
  bringtoforeground:
    git:
      url: https://github.com/GiddyNaya/bring_to_foreground.git
      ref: master
  rxdart: ^0.27.5
  timezone: ^0.9.0
  android_alarm_manager_plus: ^2.0.7+1
  disable_battery_optimization: ^1.1.0+1
  talker_flutter: ^2.0.5
  flutter_ringtone_player: ^3.2.0
  day_night_time_picker: ^1.1.3
  vibration: ^1.7.6
  flutter_vibrate: ^1.3.0
  http: ^0.13.5
  path_provider: ^2.0.11
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/audio/
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
        - asset: assets/fonts/Orbitron-Black.ttf
        - asset: assets/fonts/Orbitron-SemiBold.ttf
        - asset: assets/fonts/Orbitron-ExtraBold.ttf

  uses-material-design: true